stage 'Init'
node {
   checkout scm
   sh 'echo $ BRANCH_NAME'
}
pipeline {
    agent any;
    stages {

        stage("Test") {
            environment {
                CI = true
            }
            steps {
               sh 'npm i '
               sh 'npm test'
            }
            post {
                success{
                    publishChecks name: 'Test', title: 'Automated Tests'
                }
            }
        }

       stage("SonarQube analysis") {

            environment {
                scannerHome = tool 'sonarqube'
            }
            steps {
                script {
                    withSonarQubeEnv("sonar-aws") {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
            post {
                success{
                    publishChecks name: 'Sonar', title: 'Sonar Analysis'
                }
            }
        }


        stage('Build') {
            steps {
               sh 'npm run build'
            }
            post {
                success {
                    archiveArtifacts 'build/**/*'
                }
            }
        }

    }
}