stage 'Init'
node {
   checkout scm
   sh 'echo $ BRANCH_NAME'
}
pipeline {
    agent any;
    stages {
       stage("build & SonarQube analysis") {

            environment {
                scannerHome = tool 'sonarqube'
            }
            steps {
                script {
                    withSonarQubeEnv("sonar-aws") {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
            post {
                success{
                    publishChecks name: 'Sonar', title: 'Sonar Analysis'
                }
            }
      }

        stage('Build') {
            steps {
               sh 'npm i '
               sh 'npm run build'
            }
            post {
                success {
                    archiveArtifacts 'build/**/*'
                }
            }
        }

    }
}