stage 'Init'
node {
   checkout scm
   sh 'echo $ BRANCH_NAME'
}
pipeline {
    agent any;
    stages {
       stage("build & SonarQube analysis") {
   steps {
       script {
           withSonarQubeEnv("Sonar") {
           sh "/usr/local/sonar/bin/sonar-scanner"
               }
           }
       }
      }

        stage('Build') {
            steps {
               sh 'npm i '
               sh 'npm run build'
            }
            post {
                success {
                    archiveArtifacts 'build/**/*'
                }
            }
        }

    }
}